Nmap ssl feature
KarasyovVS/handmadesecframe pull request #6
Opened 2022-10-18 12:22 UTC by Aleksandr-Ignatev

2022-10-18 12:25 UTC, KarasyovVS commented on framework/utils/nmap_func.py
> -                        "Allowed ports left: {allowed_ports_list}".\
СКОБКИ!

2022-10-18 12:34 UTC, KarasyovVS requested changes
в целом норм, надо разобраться с именованиями

2022-10-18 12:34 UTC, KarasyovVS commented on framework/utils/nmap_func.py
> +            elif 'filtered' in elem:
СКОБКИ!

2022-10-18 12:34 UTC, KarasyovVS commented on framework/utils/nmap_func.py
> +            if 'open' in elem:
СКОБКИ!

2022-10-18 12:34 UTC, KarasyovVS commented on framework/utils/nmap_func.py
> +                        'Allowed ports left: {allowed_ports_list}'. \
СКОБКИ!

2022-10-18 12:34 UTC, KarasyovVS commented on framework/utils/nmap_func.py
> +        server_date = datetime.now()
server_date сделать переменной в параметрах функции, чтобы можно было передать кастомное значение

2022-10-18 12:34 UTC, KarasyovVS commented on framework/utils/nmap_func.py
> +        cert_expiration_date = cert_expiration_date[0].split('-')
73-75 поменять на колбасу:
cert_expiration_date = ((cert_expiration_date.split("  "))[1].split("T"))[0].split("-")

Попробовать прогнать, проверить что норм отрабатывает после замены

2022-10-18 12:34 UTC, KarasyovVS commented on tests/bdd_tests/test_bdd_tls1_2.py
> +def test_tls1_2_is_used():
Общий коммент по всему тесту - тут некорректные логи и именования, т.к. по сути в тесте мы проверяем сертификат на акред центр и дату, но не по тлс
Тлс надо выносить отдельным тестом, т.к. там другой скрипт нмапа используется

2022-10-18 12:34 UTC, KarasyovVS commented on tests/config/nmap_configs/certification_authority.py
> +    GPN_CA = 'R3'
Это серт тестового сайта?

2022-10-19 05:20 UTC, Aleksandr-Ignatev commented on tests/config/nmap_configs/certification_authority.py
> +    GPN_CA = 'R3'
Да

2022-10-19 05:26 UTC, Aleksandr-Ignatev commented on framework/utils/nmap_func.py
> +        server_date = datetime.now()
Исправил

2022-10-19 05:29 UTC, Aleksandr-Ignatev commented on framework/utils/nmap_func.py
> +        cert_expiration_date = cert_expiration_date[0].split('-')
Исправил

2022-10-19 09:56 UTC, merged